// ─────────────────────────────────────────────────────────────────────────────
// YUSHII'S PERSONALIZATION PANEL
//
// This is the single source for every personal word and media reference.
// Add real files to public/media/ and use paths such as /media/yushii-01.jpg.
// Empty media paths deliberately show respectful placeholders; no memories are
// invented by the site.
// ─────────────────────────────────────────────────────────────────────────────

export const content = {
  names: {
    her: "Yushii",
    from: "DaDDyyy",
  },
  opening: {
    eyebrow: "A TINY COSMIC TRANSMISSION",
    title: "Hey Yushii...",
    subtitle: "I made a little universe just for you.",
    button: "ENTER MY LITTLE UNIVERSE",
  },
  universeLines: [
    "Welcome to your little universe.",
    "A place made in pink stardust, with a tiny bit of kitty magic.",
    "Keep going... there is something DaDDyyy wants you to know.",
  ],
  kitty: {
    greeting: "pspsps... I was told to guide you.",
    secret: "pssst... DaDDyyy made this for you 🐱💗",
    baun: "Certified BAUNiii. 💗",
    karate: "Our little karate kid. 🥋💗",
  },
  media: {
    photos: [
      // "/media/yushii-01.jpg",
      // "/media/yushii-02.jpg",
    ],
    videos: [
      // "/media/a-little-video.mp4",
    ],
    music: "", // e.g. "/media/our-song.mp3"
  },
  memories: [
    {
      id: "photo-one",
      date: "",
      title: "",
      description: "That little look of yours... somehow it stays in my mind. 💗",
      image: "/media/yushii-left.jpg",
      video: "",
      accent: "peach",
    },
    {
      id: "photo-two",
      date: "",
      title: "",
      description: "So soft. So pretty. So completely you.",
      image: "/media/yushii-center.jpg",
      video: "",
      accent: "lilac",
    },
    {
      id: "photo-three",
      date: "",
      title: "",
      description: "Every time I see you, my heart chooses you again.",
      image: "/media/yushii-right.jpg",
      video: "",
      accent: "rose",
    },
  ],
  letter: {
    heading: "💗 Things I Want You To Know...",
    intro: "So there's something DaDDyyy wants you to know...",
    paragraphs: [
      "Yushii...",
      "There are so many things I want to tell you that sometimes I don't even know where to begin.",
      "I want you to know that I love you more than I can properly put into words.",
      "Not just because of the big things...",
      "but because of all the tiny things that make you, you.",
      "You're my little BAUNiii who somehow manages to be a karate kid one moment and then cry about being a BAUNiii the next. 😭💗",
      "And honestly?",
      "I wouldn't change that about you.",
      "I want to see you happy.",
      "I want to make you laugh when you're sad.",
      "I want to be there for the silly moments, the difficult moments, the completely random moments...",
      "all of them.",
      "And when we finally meet, I don't want that moment to be just another day.",
      "I want to finally be there with you, after all the waiting and all the conversations, and just hold you close and enjoy the fact that we're finally together.",
      "But you know what I want even more?",
      "I want a life full of stories with you.",
      "I don't want our story to end at “we met.”",
      "I want us to look back someday and have a ridiculous number of things to say:",
      "“Remember when we did that?”",
      "“Remember that trip?”",
      "“Remember how scared we were before doing that?” 😭",
      "I want to go skydiving with you.",
      "I want to try bungee jumping.",
      "I want to go paragliding.",
      "I want to do all those absolutely doom-dashin' crazy things with you that we'll probably regret five minutes before doing them. 😂💗",
      "And someday...",
      "I want us to have our own little home on wheels.",
      "Not some ordinary vehicle.",
      "A truck. A bus. A van. Something we turn into our own tiny moving home.",
      "Just imagine it.",
      "Two people.",
      "One little home.",
      "New place after new place.",
      "Waking up somewhere completely different.",
      "Looking outside and realizing we're in another part of the world.",
      "Going wherever we feel like going.",
      "Exploring places we've never seen.",
      "Collecting memories instead of things.",
      "Getting lost sometimes.",
      "Finding our way back.",
      "And having someone beside us through all of it.",
      "You.",
      "That's the kind of future I dream about.",
      "Not because I know exactly what life will look like...",
      "but because when I imagine the life I want to experience,",
      "I keep imagining you in it.",
      "So Yushii...",
      "if someday you look back at this little website,",
      "I hope you remember one thing:",
      "I love you, More than anything.",
      "More than I know how to explain.",
      "And I don't just want one beautiful moment with you.",
      "I want thousands of them.",
      "The adventures.",
      "The stupid laughs.",
      "The quiet days.",
      "The scary things.",
      "The beautiful places.",
      "The unexpected memories.",
      "I want to see the world with you.",
      "And if I get to choose who I experience all of that with...",
      "I'll choose you. Every time. 💗",
    ],
    signature: "— YOUR MAN",
  },
  adventures: {
    eyebrow: "A FUTURE I WANT TO SHARE",
    title: "Two people. One little home. The whole world.",
    copy: "Skydives, quiet roads, mountains, beaches, cities, and every unexpected place in between — not memories yet, just dreams I want to live with you.",
    items: ["skydiving", "bungee jumping", "paragliding", "new roads", "mountains", "beaches"],
  },
  proposal: {
    question: "Will you choose me?",
    yes: "YES, DaDDyyy 💗",
    ofCourse: "OF COURSE, DaDDyyy 🥺💗",
  },
  reaction: "I knew you’d say yes. 🥺💗",
  finale: {
    lines: [
      "I don't want just a moment with you, Yushii.",
      "I want a lifetime of moments.",
      "Let's go see the world. 🌎💗",
      "I love you, Yushii.",
    ],
    signature: "— Tushar",
  },
};
